import { v4 as uuidv4 } from "uuid";

export const customerData: Customer[] = [
    {
        id: "m5gr84i9",
        name: "Allison",
        lastName: "Barrezueta",
        identification: "09198992000",
        birthDate: "1997-03-27",
        gender: "female",
        email: "allisonbarrezueta@gmail.com",
        address: "KM 1.5 VIA SAMBORONDON, URB. PLAZA REAL N-7",
        city: "",
        country: "",
        zipCode: "092301",
        phone: "0995410091",
        status: "active",
        createdAt: "2021-09-01T00:00:00Z",
    },
    {
        id: "m5gr84i9",
        name: "David",
        lastName: "Perez",
        identification: "09198992000",
        birthDate: "1987-03-27",
        gender: "male",
        email: "john@mail.com",
        address: "KM 15 VIA SAMBORONDON, URB. N-7",
        city: "",
        country: "",
        zipCode: "11237",
        phone: "0995410091",
        status: "active",
        createdAt: "2021-09-01T00:00:00Z",
    },
    {
        id: "m5gr84i9",
        name: "Miguel",
        lastName: "Perez",
        identification: "09198992000",
        birthDate: "1987-03-27",
        gender: "male",
        email: "john@mail.com",
        address: "KM 15 VIA SAMBORONDON, URB. N-7",
        city: "",
        country: "",
        zipCode: "11237",
        phone: "0995410091",
        status: "active",
        createdAt: "2021-09-01T00:00:00Z",
    },
    {
        id: "m5gr84i9",
        name: "Luz",
        lastName: "Perez",
        identification: "09198992000",
        birthDate: "1987-03-27",
        gender: "male",
        email: "john@mail.com",
        address: "KM 15 VIA SAMBORONDON, URB. N-7",
        city: "",
        country: "",
        zipCode: "11237",
        phone: "0995410091",
        status: "active",
        createdAt: "2021-09-01T00:00:00Z",
    },
    {
        id: "m5gr84i9",
        name: "Vale",
        lastName: "Perez",
        identification: "09198992000",
        birthDate: "1987-03-27",
        gender: "male",
        email: "john@mail.com",
        address: "KM 15 VIA SAMBORONDON, URB. N-7",
        city: "",
        country: "",
        zipCode: "11237",
        phone: "0995410091",
        status: "active",
        createdAt: "2021-09-01T00:00:00Z",
    },
    {
        id: "m5gr84i9",
        name: "Maga",
        lastName: "Perez",
        identification: "09198992000",
        birthDate: "1987-03-27",
        gender: "male",
        email: "john@mail.com",
        address: "KM 15 VIA SAMBORONDON, URB. N-7",
        city: "",
        country: "",
        zipCode: "11237",
        phone: "0995410091",
        status: "active",
        createdAt: "2021-09-01T00:00:00Z",
    },
];

export const productsData: Product[] = [
    {
        id: uuidv4(),
        name: "PMU",
        description: "pmu asdf",
        price: 40,
        duration: 90, // typical duration of the service in minutes
        categoryId: "string",
        isActive: true,
    },
    {
        id: uuidv4(),
        name: "Cejas",
        description: "this is for cejas",
        price: 20,
        duration: 90, // typical duration of the service in minutes
        categoryId: "string",
        isActive: true,
    },
    {
        id: uuidv4(),
        name: "Lashes",
        description: "this is for lashes",
        price: 30,
        duration: 90, // typical duration of the service in minutes
        categoryId: "string",
        isActive: true,
    },
    {
        id: uuidv4(),
        name: "Lips",
        description: "this is for lips",
        price: 50,
        duration: 90, // typical duration of the service in minutes
        categoryId: "string",
        isActive: true,
    },
    {
        id: uuidv4(),
        name: "Brows",
        description: "this is for brows",
        price: 40,
        duration: 90, // typical duration of the service in minutes
        categoryId: "string",
        isActive: true,
    },
];

export const categoriesData: Category[] = [
    {
        id: uuidv4(),
        name: "PMU",
        description: "pmu asdf",
        createdAt: "2021-09-01T00:00:00Z",
    },
];

export const specialistDate: Employee[] = [
    { id: uuidv4(), name: "David", lastName: "Perez", email: "", phone: "", address: "", birthDate: "", createdAt: "2021-09-01T00:00:00Z" },
    { id: uuidv4(), name: "David", lastName: "Perez", email: "", phone: "", address: "", birthDate: "", createdAt: "2021-09-01T00:00:00Z" },
];
